Repository K4N-Studios/pan-o-phobia, pull requests merged in 2025-01, with the labels that each got.

#1 chore(doc): Adding instructions for fmod project
  doc/DEV.md
Labels: documentation

#2 Sepia effect to camera
  Assets/Prefabs.meta
  Assets/Prefabs/Sepia.prefab
  Assets/Prefabs/Sepia.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scenes/MainScene.unity.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts.meta
  Assets/Scripts/SepiaEffectManager.cs
  Assets/Scripts/SepiaEffectManager.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SceneTemplateSettings.json
Labels: feature

#4 Refactor: sepia effect to shader
  Assets/Materials.meta
  Assets/Materials/SepiaMaterial.mat
  Assets/Materials/SepiaMaterial.mat.meta
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.meta
  Assets/Scenes/MainScene.unity
  Assets/Scenes/MainScene/Global Volume Profile.asset
  Assets/Scenes/MainScene/Global Volume Profile.asset.meta
  Assets/Scenes/MainScene_Profiles.meta
  Assets/Scenes/MainScene_Profiles/Main Camera Profile 1.asset
  Assets/Scenes/MainScene_Profiles/Main Camera Profile 1.asset.meta
  Assets/Scenes/MainScene_Profiles/Main Camera Profile.asset
  Assets/Scenes/MainScene_Profiles/Main Camera Profile.asset.meta
  Assets/Scripts/Camera.meta
  Assets/Scripts/Camera/SepiaEffectRendererFeature.cs
  Assets/Scripts/Camera/SepiaEffectRendererFeature.cs.meta
  Assets/Scripts/Camera/ToggleSepiaEffect.cs
  Assets/Scripts/Camera/ToggleSepiaEffect.cs.meta
  Assets/Settings/Renderer2D.asset
  Assets/Shaders.meta
  Assets/Shaders/SepiaShader.shadergraph
  Assets/Shaders/SepiaShader.shadergraph.meta
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/TagManager.asset
Labels: feature

#5 `SepiaEffectManager` now have helpers for dealing with the alpha channel
  Assets/Prefabs/Sepia.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/SepiaEffectManager.cs
Labels: feature

#6 feat: Add PR template
  .github/pull_request_template.md
Labels: documentation, feature

#9 Global lightning
  Assets/Scenes/MainScene.unity
Labels: feature

#10 feat/collect_objects_and_interact_with_door_part_1
  Assets/Scenes/MainScene.unity
  Assets/Scenes/MainScene/PostProcess Profile.asset
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerFlashlightMovement.cs
  Assets/Scripts/Player/PlayerFlashlightMovement.cs.meta
  Assets/Scripts/Player/PlayerMovement.cs
  ProjectSettings/TagManager.asset
Labels: feature

#11 Implement footsteps events using fmod when player moves
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Player/PlayerAudioManager.cs
  Assets/Scripts/Player/PlayerAudioManager.cs.meta
  Assets/Scripts/Player/PlayerMovement.cs
Labels: feature

#12 feat: FMOD footsteps with enemies (mostly works with patrol mode)
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Enemy/EnemyAudioManager.cs
  Assets/Scripts/Enemy/EnemyAudioManager.cs.meta
  Assets/Scripts/Enemy/EnemyMovement.cs
Labels: feature

#14 feat: Made functional version of the timed switch component
  Assets/Scripts/Interactables/TimedSwitchInteractableBehavior.cs
  Assets/Scripts/Interactables/TimedSwitchInteractableBehavior.cs.meta
  Assets/Scripts/Player/PlayerInteraction.cs
Labels: feature

#18 Feature: Collectables and gamestate
  Assets/Prefabs/BedRoomLightSwitch.prefab
  Assets/Prefabs/BedRoomLightSwitch.prefab.meta
  Assets/Prefabs/MasterLightSwitch.prefab
  Assets/Prefabs/MasterLightSwitch.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameStateManager.cs
  Assets/Scripts/GameStateManager.cs.meta
  Assets/Scripts/Interactables/DoorInteractableBehavior.cs
  Assets/Scripts/Interactables/DoorInteractableBehavior.cs.meta
  Assets/Scripts/Interactables/LightSwitchInteractableBehavior.cs
  Assets/Scripts/Interactables/TimedSwitchInteractableBehavior.cs
  Assets/Scripts/Player/PlayerInteraction.cs
Labels: feature

#19 fix: remove camera from player and fix following target
  Assets/Scenes/MainScene.unity
Labels: bug

#20 Adding lightning collisions with the flashlight
  Assets/Scenes/MainScene.unity
  ProjectSettings/TagManager.asset
Labels: feature

#21 Fix/values adjustments
  Assets/Prefabs/BedroomDoor.prefab
  Assets/Prefabs/BedroomDoor.prefab.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameStateManager.cs
Labels: fix

#22 Functional doors
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Interactables/DoorInteractableBehavior.cs
  Assets/Scripts/Player/PlayerInteraction.cs
  Assets/Scripts/Scenary.meta
  Assets/Scripts/Scenary/BubblesDoorController.cs
  Assets/Scripts/Scenary/BubblesDoorController.cs.meta
  Assets/Scripts/Scenary/DoorTeleporterController.cs
  Assets/Scripts/Scenary/DoorTeleporterController.cs.meta
  ProjectSettings/TagManager.asset
Labels: feature

#23 Advanced enemy path finding
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Enemy/EnemyAudioManager.cs
  Assets/Scripts/Enemy/EnemyMovement.cs
  Assets/Scripts/Enemy/EnemySubColliderManager.cs
  Assets/Scripts/Enemy/EnemySubColliderManager.cs.meta
  ProjectSettings/TagManager.asset
Labels: feature

#24 SFX and lightning
  Assets/Prefabs/BedRoomLightSwitch.prefab
  Assets/Prefabs/FireDecoLight.prefab
  Assets/Prefabs/FireDecoLight.prefab.meta
  Assets/Prefabs/MasterLightSwitch.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Interactables/LightSwitchInteractableBehavior.cs
  Assets/Scripts/Interactables/TimedSwitchInteractableBehavior.cs
Labels: feature

#25 Global collider on bubbles instead of static collider when opening the bubble as a door
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Interactables/BubbleDoorInteractableBehavior.cs
  Assets/Scripts/Interactables/BubbleDoorInteractableBehavior.cs.meta
Labels: feature

#27 feat: Make flashlight work as a real collectable, player will have to collect the flashlight object in order to be able to toggle his flashlight
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameStateManager.cs
  Assets/Scripts/Player/PlayerFlashlightManager.cs
  Assets/Scripts/Player/PlayerFlashlightManager.cs.meta
Labels: feature

#28 feat: Detect player around interactable
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Collectables/Interactable.cs
  Assets/Scripts/Player/PlayerInteraction.cs
Labels: feature

#30 feat: Add black overlay while going through doors
  Assets/Scenes/MainScene.unity
  Assets/Scripts/HUD/BlackOverlayComponent.cs
  Assets/Scripts/HUD/BlackOverlayComponent.cs.meta
  Assets/Scripts/HUD/FadeController.cs
  Assets/Scripts/HUD/FadeController.cs.meta
  Assets/Scripts/Player/PlayerFlashlightManager.cs
  Assets/Scripts/Scenary/DoorTeleporterController.cs
  ProjectSettings/TagManager.asset
Labels: feature

#32 Add UI for stats and lots of fixes
  Assets/Images/UI.meta
  Assets/Images/UI/circle.png
  Assets/Images/UI/circle.png.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Enemy/EnemyAttack.cs
  Assets/Scripts/GameStateManager.cs
  Assets/Scripts/HUD/ScopedLightTimerComponent.cs
  Assets/Scripts/HUD/ScopedLightTimerComponent.cs.meta
  Assets/Scripts/Interactables/BubbleDoorInteractableBehavior.cs
  Assets/Scripts/Interactables/TimedSwitchInteractableBehavior.cs
  Assets/Scripts/Player/PlayerStress.cs
  Assets/Scripts/Player/PlayerStress.cs.meta
  ProjectSettings/TagManager.asset
Labels: feature

#36 FMOD integration main bg
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Interactables/LightSwitchInteractableBehavior.cs
  Assets/Scripts/Interactables/TimedSwitchInteractableBehavior.cs
  Assets/Scripts/Scenary/MainBackgroundMusic.cs
  Assets/Scripts/Scenary/MainBackgroundMusic.cs.meta
Labels: feature

#37 Add dynamic background music with layers component
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Scenary/MainBackgroundMusic.cs
Labels: feature

#39 FMOD SFX
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Enemy/EnemyAttack.cs
  Assets/Scripts/HUD/ScopedLightTimerComponent.cs
  Assets/Scripts/Interactables/DoorInteractableBehavior.cs
  Assets/Scripts/Player/PlayerAudioManager.cs
  Assets/Scripts/Scenary/DoorTeleporterController.cs
  Assets/Scripts/Scenary/MainBackgroundMusic.cs
Labels: feature

#40 feat: Typewritter dialog component
  Assets/Images/UI/chevron-down-white.png
  Assets/Images/UI/chevron-down-white.png.meta
  Assets/Images/UI/circular-progress.png
  Assets/Images/UI/circular-progress.png.meta
  Assets/Images/UI/heart-broken.png
  Assets/Images/UI/heart-broken.png.meta
  Assets/Images/UI/heart.png
  Assets/Images/UI/heart.png.meta
  Assets/Images/UI/light-bulb-broken.png
  Assets/Images/UI/light-bulb-broken.png.meta
  Assets/Images/UI/light-bulb.png
  Assets/Images/UI/light-bulb.png.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameStateManager.cs
  Assets/Scripts/HUD/DialogTypewritterComponent.cs
  Assets/Scripts/HUD/DialogTypewritterComponent.cs.meta
  Assets/Scripts/MainMenu/MainMenuController.cs
Labels: feature

#42 Add scripts for new status elements on the HUD
  Assets/Images/UI/face-depressed.png
  Assets/Images/UI/face-depressed.png.meta
  Assets/Images/UI/face-normal.png
  Assets/Images/UI/face-normal.png.meta
  Assets/Prefabs/Player.prefab
  Assets/Scenes/MainScene.unity
  Assets/Scripts/HUD/PlayerHealthIndicator.cs
  Assets/Scripts/HUD/PlayerHealthIndicator.cs.meta
  Assets/Scripts/HUD/PlayerStressIndicator.cs
  Assets/Scripts/HUD/PlayerStressIndicator.cs.meta
  Assets/Scripts/Player/PlayerStress.cs
Labels: feature

#43 Implement semi broken player attack feature
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Enemy/EnemyAttack.cs
  Assets/Scripts/Enemy/EnemyHealth.cs
  Assets/Scripts/Player/PlayerAttack.cs
  Assets/Scripts/Player/PlayerAttack.cs.meta
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/Player/PlayerInteraction.cs
Labels: feature

#46 Add cracking wood sound effect when no lights are turned on
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/HUD/FearCrackingWoodAudio.cs
  Assets/Scripts/HUD/FearCrackingWoodAudio.cs.meta
  Assets/Scripts/Interactables/BubbleDoorInteractableBehavior.cs
  Assets/Scripts/Player/PlayerStress.cs
Labels: feature

#47 Add gameover splash (first ver)
  Assets/Images/Cameo.meta
  Assets/Images/Cameo/personaje-cameo.png
  Assets/Images/Cameo/personaje-cameo.png.meta
  Assets/Scenes/MainScene.unity
  Assets/Scripts/GameStateManager.cs
  Assets/Scripts/HUD/DialogTypewritterComponent.cs
  Assets/Scripts/HUD/FearCrackingWoodAudio.cs
  Assets/Scripts/Player/PlayerHealth.cs
  Assets/Scripts/Scenary/MainBackgroundMusic.cs
Labels: feature

#48 Add gameover mechanic when the stress if it's full
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Scenes/MainScene.unity
  Assets/Scripts/Player/PlayerInteraction.cs
  Assets/Scripts/Player/PlayerStress.cs
Labels: feature

#51 Add missing sfx for light switches
  Assets/Prefabs/BedRoomLightSwitch.prefab
  Assets/Prefabs/MasterLightSwitch.prefab
  Assets/Scenes/MainScene.unity
Labels: feature

#52 Hide trigger that was supposed to be invisible originally
  Assets/Scenes/MainScene.unity
Labels: feature
